language: node_js

node_js:
  - "0.10"

services:
  - mysql

before_script:
  - mysql -e 'create database myapp_test;'
  - cp ./test/config/local.js ./config/local.js

notifications:
  email: true

# whitelisted branches
branches:
  only:
    - master